/* Generated from Lynncat Markets ShuihuCards.swift. */
window.SHUIHU_CARDS = [
  {
    "id": 1,
    "star": "天魁星",
    "nickname": "呼保义",
    "name": "宋江",
    "role": "梁山总兵都头领 / Chief",
    "weapon": "令旗",
    "signature": "及时雨，善聚人心",
    "command": 98,
    "might": 62,
    "wisdom": 88,
    "charisma": 99
  },
  {
    "id": 2,
    "star": "天罡星",
    "nickname": "玉麒麟",
    "name": "卢俊义",
    "role": "梁山总兵都头领 / Chief",
    "weapon": "麒麟黄金矛",
    "signature": "河北豪杰，棍棒无双",
    "command": 92,
    "might": 99,
    "wisdom": 78,
    "charisma": 90
  },
  {
    "id": 3,
    "star": "天机星",
    "nickname": "智多星",
    "name": "吴用",
    "role": "掌管机密军师 / Strategist",
    "weapon": "羽扇",
    "signature": "运筹帷幄，智取生辰纲",
    "command": 94,
    "might": 42,
    "wisdom": 100,
    "charisma": 84
  },
  {
    "id": 4,
    "star": "天闲星",
    "nickname": "入云龙",
    "name": "公孙胜",
    "role": "掌管机密军师 / Taoist",
    "weapon": "松纹古剑",
    "signature": "呼风唤雨，五雷天罡",
    "command": 86,
    "might": 79,
    "wisdom": 96,
    "charisma": 88
  },
  {
    "id": 5,
    "star": "天勇星",
    "nickname": "大刀",
    "name": "关胜",
    "role": "马军五虎将 / Cavalry General",
    "weapon": "青龙偃月刀",
    "signature": "将门风骨，刀势沉雄",
    "command": 94,
    "might": 97,
    "wisdom": 82,
    "charisma": 91
  },
  {
    "id": 6,
    "star": "天雄星",
    "nickname": "豹子头",
    "name": "林冲",
    "role": "马军五虎将 / Cavalry General",
    "weapon": "丈八蛇矛",
    "signature": "八十万禁军教头",
    "command": 91,
    "might": 98,
    "wisdom": 82,
    "charisma": 88
  },
  {
    "id": 7,
    "star": "天猛星",
    "nickname": "霹雳火",
    "name": "秦明",
    "role": "马军五虎将 / Cavalry General",
    "weapon": "狼牙棒",
    "signature": "性烈如火，冲阵如雷",
    "command": 87,
    "might": 96,
    "wisdom": 68,
    "charisma": 80
  },
  {
    "id": 8,
    "star": "天威星",
    "nickname": "双鞭",
    "name": "呼延灼",
    "role": "马军五虎将 / Cavalry General",
    "weapon": "水磨八棱双鞭",
    "signature": "连环甲马，名将之后",
    "command": 95,
    "might": 94,
    "wisdom": 84,
    "charisma": 87
  },
  {
    "id": 9,
    "star": "天英星",
    "nickname": "小李广",
    "name": "花荣",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "天地日月弓",
    "signature": "百步穿杨，银枪神箭",
    "command": 88,
    "might": 96,
    "wisdom": 82,
    "charisma": 94
  },
  {
    "id": 10,
    "star": "天贵星",
    "nickname": "小旋风",
    "name": "柴进",
    "role": "掌管钱粮 / Treasurer",
    "weapon": "丹书铁券",
    "signature": "仗义疏财，礼贤下士",
    "command": 78,
    "might": 70,
    "wisdom": 83,
    "charisma": 98
  },
  {
    "id": 11,
    "star": "天富星",
    "nickname": "扑天雕",
    "name": "李应",
    "role": "掌管钱粮 / Treasurer",
    "weapon": "浑铁点钢枪",
    "signature": "飞刀五口，雄踞李庄",
    "command": 84,
    "might": 91,
    "wisdom": 84,
    "charisma": 88
  },
  {
    "id": 12,
    "star": "天满星",
    "nickname": "美髯公",
    "name": "朱仝",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "九龙朝阳刀",
    "signature": "美髯重义，神似关公",
    "command": 85,
    "might": 91,
    "wisdom": 77,
    "charisma": 94
  },
  {
    "id": 13,
    "star": "天孤星",
    "nickname": "花和尚",
    "name": "鲁智深",
    "role": "步军头领 / Infantry Captain",
    "weapon": "水磨禅杖",
    "signature": "倒拔垂杨柳，拳打镇关西",
    "command": 82,
    "might": 99,
    "wisdom": 74,
    "charisma": 95
  },
  {
    "id": 14,
    "star": "天伤星",
    "nickname": "行者",
    "name": "武松",
    "role": "步军头领 / Infantry Captain",
    "weapon": "雪花镔铁双刀",
    "signature": "景阳冈打虎，醉打蒋门神",
    "command": 80,
    "might": 100,
    "wisdom": 78,
    "charisma": 96
  },
  {
    "id": 15,
    "star": "天立星",
    "nickname": "双枪将",
    "name": "董平",
    "role": "马军五虎将 / Cavalry General",
    "weapon": "出白梨花双枪",
    "signature": "双枪飞舞，风流万户侯",
    "command": 86,
    "might": 96,
    "wisdom": 72,
    "charisma": 88
  },
  {
    "id": 16,
    "star": "天捷星",
    "nickname": "没羽箭",
    "name": "张清",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "飞凰火石",
    "signature": "飞石连打十五将",
    "command": 82,
    "might": 95,
    "wisdom": 80,
    "charisma": 88
  },
  {
    "id": 17,
    "star": "天暗星",
    "nickname": "青面兽",
    "name": "杨志",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "祖传宝刀",
    "signature": "杨家将后，卖刀斗牛二",
    "command": 86,
    "might": 94,
    "wisdom": 79,
    "charisma": 82
  },
  {
    "id": 18,
    "star": "天佑星",
    "nickname": "金枪手",
    "name": "徐宁",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "钩镰枪",
    "signature": "金枪班教师，大破连环马",
    "command": 87,
    "might": 93,
    "wisdom": 85,
    "charisma": 86
  },
  {
    "id": 19,
    "star": "天空星",
    "nickname": "急先锋",
    "name": "索超",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "金蘸斧",
    "signature": "性急争先，斧劈阵门",
    "command": 79,
    "might": 91,
    "wisdom": 62,
    "charisma": 77
  },
  {
    "id": 20,
    "star": "天速星",
    "nickname": "神行太保",
    "name": "戴宗",
    "role": "总探声息头领 / Courier",
    "weapon": "甲马神符",
    "signature": "日行八百，飞报军情",
    "command": 80,
    "might": 72,
    "wisdom": 86,
    "charisma": 88
  },
  {
    "id": 21,
    "star": "天异星",
    "nickname": "赤发鬼",
    "name": "刘唐",
    "role": "步军头领 / Infantry Captain",
    "weapon": "朴刀",
    "signature": "赤发朱砂，夜奔东溪村",
    "command": 74,
    "might": 91,
    "wisdom": 68,
    "charisma": 79
  },
  {
    "id": 22,
    "star": "天杀星",
    "nickname": "黑旋风",
    "name": "李逵",
    "role": "步军头领 / Infantry Captain",
    "weapon": "板斧双持",
    "signature": "嫉恶如仇，沂岭杀四虎",
    "command": 68,
    "might": 98,
    "wisdom": 45,
    "charisma": 86
  },
  {
    "id": 23,
    "star": "天微星",
    "nickname": "九纹龙",
    "name": "史进",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "三尖两刃刀",
    "signature": "身纹九龙，十八般武艺",
    "command": 80,
    "might": 92,
    "wisdom": 70,
    "charisma": 90
  },
  {
    "id": 24,
    "star": "天究星",
    "nickname": "没遮拦",
    "name": "穆弘",
    "role": "马军八骠骑 / Vanguard",
    "weapon": "朴刀",
    "signature": "揭阳镇豪杰，气势无拦",
    "command": 79,
    "might": 89,
    "wisdom": 67,
    "charisma": 82
  },
  {
    "id": 25,
    "star": "天退星",
    "nickname": "插翅虎",
    "name": "雷横",
    "role": "步军头领 / Infantry Captain",
    "weapon": "朴刀",
    "signature": "膂力过人，跳涧如虎",
    "command": 76,
    "might": 88,
    "wisdom": 65,
    "charisma": 78
  },
  {
    "id": 26,
    "star": "天寿星",
    "nickname": "混江龙",
    "name": "李俊",
    "role": "水军都督 / Naval Admiral",
    "weapon": "七星宝剑",
    "signature": "水战统帅，海外称王",
    "command": 95,
    "might": 88,
    "wisdom": 91,
    "charisma": 93
  },
  {
    "id": 27,
    "star": "天剑星",
    "nickname": "立地太岁",
    "name": "阮小二",
    "role": "水军头领 / Naval Captain",
    "weapon": "分水鱼叉",
    "signature": "石碣村长兄，水寨先锋",
    "command": 83,
    "might": 88,
    "wisdom": 72,
    "charisma": 84
  },
  {
    "id": 28,
    "star": "天平星",
    "nickname": "船火儿",
    "name": "张横",
    "role": "水军头领 / Naval Captain",
    "weapon": "鱼叉",
    "signature": "浔阳江艄公，浪里截舟",
    "command": 78,
    "might": 88,
    "wisdom": 66,
    "charisma": 75
  },
  {
    "id": 29,
    "star": "天罪星",
    "nickname": "短命二郎",
    "name": "阮小五",
    "role": "水军头领 / Naval Captain",
    "weapon": "短刀鱼叉",
    "signature": "水性剽悍，性烈不羁",
    "command": 77,
    "might": 89,
    "wisdom": 68,
    "charisma": 78
  },
  {
    "id": 30,
    "star": "天损星",
    "nickname": "浪里白条",
    "name": "张顺",
    "role": "水军头领 / Naval Captain",
    "weapon": "分水刺",
    "signature": "水底伏七日，浪里疾如鱼",
    "command": 82,
    "might": 90,
    "wisdom": 76,
    "charisma": 91
  },
  {
    "id": 31,
    "star": "天败星",
    "nickname": "活阎罗",
    "name": "阮小七",
    "role": "水军头领 / Naval Captain",
    "weapon": "竹篙弯刀",
    "signature": "快意豪放，倒船盗御酒",
    "command": 75,
    "might": 88,
    "wisdom": 64,
    "charisma": 89
  },
  {
    "id": 32,
    "star": "天牢星",
    "nickname": "病关索",
    "name": "杨雄",
    "role": "步军头领 / Infantry Captain",
    "weapon": "冷艳锯齿刀",
    "signature": "刽子手出身，行事果决",
    "command": 76,
    "might": 89,
    "wisdom": 71,
    "charisma": 78
  },
  {
    "id": 33,
    "star": "天慧星",
    "nickname": "拼命三郎",
    "name": "石秀",
    "role": "步军头领 / Infantry Captain",
    "weapon": "雁翎刀",
    "signature": "路见不平，劫法场拼命",
    "command": 78,
    "might": 92,
    "wisdom": 82,
    "charisma": 88
  },
  {
    "id": 34,
    "star": "天暴星",
    "nickname": "两头蛇",
    "name": "解珍",
    "role": "步军头领 / Hunter",
    "weapon": "浑铁点钢叉",
    "signature": "登州猎户，翻山逐虎",
    "command": 75,
    "might": 89,
    "wisdom": 72,
    "charisma": 79
  },
  {
    "id": 35,
    "star": "天哭星",
    "nickname": "双尾蝎",
    "name": "解宝",
    "role": "步军头领 / Hunter",
    "weapon": "浑铁点钢叉",
    "signature": "攀崖涉险，毒蝎双钩",
    "command": 73,
    "might": 88,
    "wisdom": 71,
    "charisma": 77
  },
  {
    "id": 36,
    "star": "天巧星",
    "nickname": "浪子",
    "name": "燕青",
    "role": "步军头领 / Scout",
    "weapon": "川弩短弓",
    "signature": "相扑绝技，吹箫唱曲",
    "command": 84,
    "might": 92,
    "wisdom": 92,
    "charisma": 99
  },
  {
    "id": 37,
    "star": "地魁星",
    "nickname": "神机军师",
    "name": "朱武",
    "role": "参赞军务 / Strategist",
    "weapon": "双刀阵图",
    "signature": "精通阵法，善使双刀",
    "command": 88,
    "might": 73,
    "wisdom": 95,
    "charisma": 82
  },
  {
    "id": 38,
    "star": "地煞星",
    "nickname": "镇三山",
    "name": "黄信",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "丧门剑",
    "signature": "镇守青州三山",
    "command": 76,
    "might": 84,
    "wisdom": 67,
    "charisma": 76
  },
  {
    "id": 39,
    "star": "地勇星",
    "nickname": "病尉迟",
    "name": "孙立",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "竹节虎眼鞭",
    "signature": "登州兵马提辖，枪鞭双绝",
    "command": 87,
    "might": 94,
    "wisdom": 82,
    "charisma": 85
  },
  {
    "id": 40,
    "star": "地杰星",
    "nickname": "丑郡马",
    "name": "宣赞",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "钢刀",
    "signature": "连珠箭胜番将，铁面忠勇",
    "command": 78,
    "might": 86,
    "wisdom": 70,
    "charisma": 68
  },
  {
    "id": 41,
    "star": "地雄星",
    "nickname": "井木犴",
    "name": "郝思文",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "长枪",
    "signature": "熟谙兵法，与关胜同袍",
    "command": 80,
    "might": 85,
    "wisdom": 78,
    "charisma": 77
  },
  {
    "id": 42,
    "star": "地威星",
    "nickname": "百胜将",
    "name": "韩滔",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "枣木槊",
    "signature": "团练使出身，百战先锋",
    "command": 79,
    "might": 84,
    "wisdom": 71,
    "charisma": 75
  },
  {
    "id": 43,
    "star": "地英星",
    "nickname": "天目将",
    "name": "彭玘",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "三尖两刃刀",
    "signature": "眉心天目，善使飞叉",
    "command": 75,
    "might": 84,
    "wisdom": 68,
    "charisma": 74
  },
  {
    "id": 44,
    "star": "地奇星",
    "nickname": "圣水将军",
    "name": "单廷珪",
    "role": "马军小彪将 / Water General",
    "weapon": "黑杆水枪",
    "signature": "玄水破敌，黑甲黑马",
    "command": 80,
    "might": 84,
    "wisdom": 79,
    "charisma": 77
  },
  {
    "id": 45,
    "star": "地猛星",
    "nickname": "神火将军",
    "name": "魏定国",
    "role": "马军小彪将 / Fire General",
    "weapon": "熟铜刀",
    "signature": "火攻冲阵，红甲赤马",
    "command": 81,
    "might": 85,
    "wisdom": 78,
    "charisma": 78
  },
  {
    "id": 46,
    "star": "地文星",
    "nickname": "圣手书生",
    "name": "萧让",
    "role": "文书营造 / Calligrapher",
    "weapon": "湖笔书卷",
    "signature": "精通诸体，仿写文书",
    "command": 62,
    "might": 45,
    "wisdom": 94,
    "charisma": 84
  },
  {
    "id": 47,
    "star": "地正星",
    "nickname": "铁面孔目",
    "name": "裴宣",
    "role": "军政司赏罚 / Magistrate",
    "weapon": "阴阳双剑",
    "signature": "铁面无私，赏罚分明",
    "command": 78,
    "might": 72,
    "wisdom": 91,
    "charisma": 82
  },
  {
    "id": 48,
    "star": "地阔星",
    "nickname": "摩云金翅",
    "name": "欧鹏",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "铁枪",
    "signature": "身健步快，如金翅摩云",
    "command": 74,
    "might": 84,
    "wisdom": 66,
    "charisma": 73
  },
  {
    "id": 49,
    "star": "地阖星",
    "nickname": "火眼狻猊",
    "name": "邓飞",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "铁链",
    "signature": "双眼赤红，铁链横扫",
    "command": 74,
    "might": 85,
    "wisdom": 64,
    "charisma": 74
  },
  {
    "id": 50,
    "star": "地强星",
    "nickname": "锦毛虎",
    "name": "燕顺",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "朴刀",
    "signature": "清风山寨主，锦衣虎胆",
    "command": 73,
    "might": 83,
    "wisdom": 65,
    "charisma": 76
  },
  {
    "id": 51,
    "star": "地暗星",
    "nickname": "锦豹子",
    "name": "杨林",
    "role": "马军小彪将 / Scout",
    "weapon": "朴刀",
    "signature": "四海结交，探路引线",
    "command": 70,
    "might": 79,
    "wisdom": 76,
    "charisma": 82
  },
  {
    "id": 52,
    "star": "地轴星",
    "nickname": "轰天雷",
    "name": "凌振",
    "role": "火炮营造 / Artillery Chief",
    "weapon": "风火炮",
    "signature": "宋代第一炮手，雷震城郭",
    "command": 72,
    "might": 58,
    "wisdom": 89,
    "charisma": 76
  },
  {
    "id": 53,
    "star": "地会星",
    "nickname": "神算子",
    "name": "蒋敬",
    "role": "钱粮核算 / Accountant",
    "weapon": "算盘",
    "signature": "心算如神，掌理钱粮",
    "command": 71,
    "might": 46,
    "wisdom": 96,
    "charisma": 78
  },
  {
    "id": 54,
    "star": "地佐星",
    "nickname": "小温侯",
    "name": "吕方",
    "role": "中军守护 / Guard",
    "weapon": "方天画戟",
    "signature": "红袍画戟，小吕布之风",
    "command": 76,
    "might": 87,
    "wisdom": 66,
    "charisma": 84
  },
  {
    "id": 55,
    "star": "地佑星",
    "nickname": "赛仁贵",
    "name": "郭盛",
    "role": "中军守护 / Guard",
    "weapon": "方天画戟",
    "signature": "白袍银戟，戟缨交缠",
    "command": 75,
    "might": 86,
    "wisdom": 65,
    "charisma": 83
  },
  {
    "id": 56,
    "star": "地灵星",
    "nickname": "神医",
    "name": "安道全",
    "role": "医护营 / Physician",
    "weapon": "银针药囊",
    "signature": "妙手回春，内外科皆精",
    "command": 68,
    "might": 40,
    "wisdom": 98,
    "charisma": 91
  },
  {
    "id": 57,
    "star": "地兽星",
    "nickname": "紫髯伯",
    "name": "皇甫端",
    "role": "兽医营 / Veterinarian",
    "weapon": "药葫芦",
    "signature": "碧眼黄须，专医战马",
    "command": 64,
    "might": 48,
    "wisdom": 91,
    "charisma": 80
  },
  {
    "id": 58,
    "star": "地微星",
    "nickname": "矮脚虎",
    "name": "王英",
    "role": "马军头领 / Cavalry Scout",
    "weapon": "丈八长枪",
    "signature": "五短身材，山路悍斗",
    "command": 57,
    "might": 76,
    "wisdom": 47,
    "charisma": 58
  },
  {
    "id": 59,
    "star": "地慧星",
    "nickname": "一丈青",
    "name": "扈三娘",
    "role": "马军头领 / Cavalry Scout",
    "weapon": "日月双刀",
    "signature": "红锦套索，双刀擒将",
    "command": 80,
    "might": 92,
    "wisdom": 77,
    "charisma": 91
  },
  {
    "id": 60,
    "star": "地暴星",
    "nickname": "丧门神",
    "name": "鲍旭",
    "role": "步军将校 / Infantry",
    "weapon": "阔剑",
    "signature": "黑衣阔剑，嗜战冲阵",
    "command": 63,
    "might": 88,
    "wisdom": 45,
    "charisma": 62
  },
  {
    "id": 61,
    "star": "地默星",
    "nickname": "混世魔王",
    "name": "樊瑞",
    "role": "芒砀山头领 / Mystic",
    "weapon": "流星锤",
    "signature": "会使妖法，剑锤并用",
    "command": 76,
    "might": 85,
    "wisdom": 87,
    "charisma": 80
  },
  {
    "id": 62,
    "star": "地猖星",
    "nickname": "毛头星",
    "name": "孔明",
    "role": "守护中军 / Guard",
    "weapon": "朴刀",
    "signature": "白虎山兄长，豪气外露",
    "command": 65,
    "might": 76,
    "wisdom": 54,
    "charisma": 68
  },
  {
    "id": 63,
    "star": "地狂星",
    "nickname": "独火星",
    "name": "孔亮",
    "role": "守护中军 / Guard",
    "weapon": "朴刀",
    "signature": "性急如火，随兄闯荡",
    "command": 61,
    "might": 74,
    "wisdom": 50,
    "charisma": 65
  },
  {
    "id": 64,
    "star": "地飞星",
    "nickname": "八臂哪吒",
    "name": "项充",
    "role": "步军牌手 / Shield Trooper",
    "weapon": "飞刀蛮牌",
    "signature": "二十四把飞刀，八臂齐发",
    "command": 72,
    "might": 86,
    "wisdom": 72,
    "charisma": 78
  },
  {
    "id": 65,
    "star": "地走星",
    "nickname": "飞天大圣",
    "name": "李衮",
    "role": "步军牌手 / Shield Trooper",
    "weapon": "标枪团牌",
    "signature": "二十四支标枪，团牌滚阵",
    "command": 71,
    "might": 85,
    "wisdom": 70,
    "charisma": 77
  },
  {
    "id": 66,
    "star": "地巧星",
    "nickname": "玉臂匠",
    "name": "金大坚",
    "role": "印信营造 / Seal Carver",
    "weapon": "玉石刻刀",
    "signature": "善刻碑印，玉臂精工",
    "command": 61,
    "might": 43,
    "wisdom": 93,
    "charisma": 79
  },
  {
    "id": 67,
    "star": "地明星",
    "nickname": "铁笛仙",
    "name": "马麟",
    "role": "马军小彪将 / Musician",
    "weapon": "铁笛大滚刀",
    "signature": "铁笛能歌，双刀能战",
    "command": 70,
    "might": 81,
    "wisdom": 70,
    "charisma": 86
  },
  {
    "id": 68,
    "star": "地进星",
    "nickname": "出洞蛟",
    "name": "童威",
    "role": "水军头领 / Naval Captain",
    "weapon": "鱼叉",
    "signature": "浔阳江水贩，入水如蛟",
    "command": 74,
    "might": 82,
    "wisdom": 67,
    "charisma": 75
  },
  {
    "id": 69,
    "star": "地退星",
    "nickname": "翻江蜃",
    "name": "童猛",
    "role": "水军头领 / Naval Captain",
    "weapon": "水叉",
    "signature": "翻江搅浪，与兄同舟",
    "command": 72,
    "might": 81,
    "wisdom": 65,
    "charisma": 73
  },
  {
    "id": 70,
    "star": "地满星",
    "nickname": "玉幡竿",
    "name": "孟康",
    "role": "战船营造 / Shipwright",
    "weapon": "船斧",
    "signature": "身长肤白，督造战船",
    "command": 69,
    "might": 72,
    "wisdom": 81,
    "charisma": 75
  },
  {
    "id": 71,
    "star": "地遂星",
    "nickname": "通臂猿",
    "name": "侯健",
    "role": "旌旗袍服 / Tailor",
    "weapon": "银针软尺",
    "signature": "猿臂灵巧，裁制军旗",
    "command": 62,
    "might": 59,
    "wisdom": 88,
    "charisma": 78
  },
  {
    "id": 72,
    "star": "地周星",
    "nickname": "跳涧虎",
    "name": "陈达",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "出白点钢枪",
    "signature": "少华山先锋，跃涧突阵",
    "command": 66,
    "might": 79,
    "wisdom": 55,
    "charisma": 67
  },
  {
    "id": 73,
    "star": "地隐星",
    "nickname": "白花蛇",
    "name": "杨春",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "大杆刀",
    "signature": "白衣长身，刀路如蛇",
    "command": 66,
    "might": 78,
    "wisdom": 58,
    "charisma": 68
  },
  {
    "id": 74,
    "star": "地异星",
    "nickname": "白面郎君",
    "name": "郑天寿",
    "role": "步军将校 / Infantry",
    "weapon": "雁翎刀",
    "signature": "白面俊秀，清风山三当家",
    "command": 64,
    "might": 77,
    "wisdom": 59,
    "charisma": 76
  },
  {
    "id": 75,
    "star": "地理星",
    "nickname": "九尾龟",
    "name": "陶宗旺",
    "role": "城垣营造 / Builder",
    "weapon": "铁锹",
    "signature": "庄户出身，筑城开道",
    "command": 71,
    "might": 75,
    "wisdom": 70,
    "charisma": 73
  },
  {
    "id": 76,
    "star": "地俊星",
    "nickname": "铁扇子",
    "name": "宋清",
    "role": "宴席供应 / Steward",
    "weapon": "铁扇",
    "signature": "谦和稳重，主管筵宴",
    "command": 67,
    "might": 45,
    "wisdom": 74,
    "charisma": 84
  },
  {
    "id": 77,
    "star": "地乐星",
    "nickname": "铁叫子",
    "name": "乐和",
    "role": "机密传报 / Singer",
    "weapon": "铁叫子",
    "signature": "聪敏善歌，诸般乐品皆晓",
    "command": 67,
    "might": 61,
    "wisdom": 86,
    "charisma": 91
  },
  {
    "id": 78,
    "star": "地捷星",
    "nickname": "花项虎",
    "name": "龚旺",
    "role": "步军将校 / Infantry",
    "weapon": "飞枪",
    "signature": "虎斑刺项，马上飞枪",
    "command": 65,
    "might": 78,
    "wisdom": 57,
    "charisma": 67
  },
  {
    "id": 79,
    "star": "地速星",
    "nickname": "中箭虎",
    "name": "丁得孙",
    "role": "步军将校 / Infantry",
    "weapon": "飞叉",
    "signature": "面颊箭痕，马上飞叉",
    "command": 64,
    "might": 77,
    "wisdom": 56,
    "charisma": 66
  },
  {
    "id": 80,
    "star": "地镇星",
    "nickname": "小遮拦",
    "name": "穆春",
    "role": "步军将校 / Infantry",
    "weapon": "朴刀",
    "signature": "揭阳镇少主，水路遮拦",
    "command": 64,
    "might": 75,
    "wisdom": 55,
    "charisma": 68
  },
  {
    "id": 81,
    "star": "地羁星",
    "nickname": "操刀鬼",
    "name": "曹正",
    "role": "屠宰供应 / Butcher",
    "weapon": "剔骨尖刀",
    "signature": "林冲徒弟，善剔牲口",
    "command": 64,
    "might": 78,
    "wisdom": 64,
    "charisma": 70
  },
  {
    "id": 82,
    "star": "地魔星",
    "nickname": "云里金刚",
    "name": "宋万",
    "role": "步军将校 / Infantry",
    "weapon": "长枪",
    "signature": "身躯高大，梁山元老",
    "command": 65,
    "might": 78,
    "wisdom": 48,
    "charisma": 67
  },
  {
    "id": 83,
    "star": "地妖星",
    "nickname": "摸着天",
    "name": "杜迁",
    "role": "步军将校 / Infantry",
    "weapon": "朴刀",
    "signature": "身长臂展，梁山开山头领",
    "command": 64,
    "might": 76,
    "wisdom": 49,
    "charisma": 66
  },
  {
    "id": 84,
    "star": "地幽星",
    "nickname": "病大虫",
    "name": "薛永",
    "role": "步军将校 / Martial Artist",
    "weapon": "花枪",
    "signature": "江湖卖艺，棒法沉稳",
    "command": 65,
    "might": 80,
    "wisdom": 61,
    "charisma": 72
  },
  {
    "id": 85,
    "star": "地伏星",
    "nickname": "金眼彪",
    "name": "施恩",
    "role": "步军将校 / Infantry",
    "weapon": "棍棒",
    "signature": "快活林少管营，重情知恩",
    "command": 63,
    "might": 74,
    "wisdom": 64,
    "charisma": 77
  },
  {
    "id": 86,
    "star": "地僻星",
    "nickname": "打虎将",
    "name": "李忠",
    "role": "步军将校 / Infantry",
    "weapon": "梨花枪",
    "signature": "卖药使枪，桃花山寨主",
    "command": 61,
    "might": 72,
    "wisdom": 53,
    "charisma": 65
  },
  {
    "id": 87,
    "star": "地空星",
    "nickname": "小霸王",
    "name": "周通",
    "role": "马军小彪将 / Cavalry Scout",
    "weapon": "走水绿沉枪",
    "signature": "桃花山寨主，性情直露",
    "command": 60,
    "might": 74,
    "wisdom": 51,
    "charisma": 64
  },
  {
    "id": 88,
    "star": "地孤星",
    "nickname": "金钱豹子",
    "name": "汤隆",
    "role": "军器营造 / Armorer",
    "weapon": "铁瓜锤",
    "signature": "遍体金钱斑，锻造钩镰枪",
    "command": 70,
    "might": 82,
    "wisdom": 82,
    "charisma": 70
  },
  {
    "id": 89,
    "star": "地全星",
    "nickname": "鬼脸儿",
    "name": "杜兴",
    "role": "南山酒店 / Steward",
    "weapon": "鬼头刀",
    "signature": "面貌狰狞，办事老练",
    "command": 66,
    "might": 72,
    "wisdom": 72,
    "charisma": 69
  },
  {
    "id": 90,
    "star": "地短星",
    "nickname": "出林龙",
    "name": "邹渊",
    "role": "步军将校 / Infantry",
    "weapon": "朴刀",
    "signature": "登云山头领，出林争雄",
    "command": 63,
    "might": 77,
    "wisdom": 57,
    "charisma": 66
  },
  {
    "id": 91,
    "star": "地角星",
    "nickname": "独角龙",
    "name": "邹润",
    "role": "步军将校 / Infantry",
    "weapon": "铁头功",
    "signature": "额生肉角，一头撞折松树",
    "command": 66,
    "might": 84,
    "wisdom": 60,
    "charisma": 70
  },
  {
    "id": 92,
    "star": "地囚星",
    "nickname": "旱地忽律",
    "name": "朱贵",
    "role": "南山酒店 / Scout",
    "weapon": "鹊画弓",
    "signature": "梁山耳目，水亭施号箭",
    "command": 72,
    "might": 68,
    "wisdom": 84,
    "charisma": 78
  },
  {
    "id": 93,
    "star": "地藏星",
    "nickname": "笑面虎",
    "name": "朱富",
    "role": "酿造供应 / Brewer",
    "weapon": "麻药酒",
    "signature": "笑里藏机，巧救李云",
    "command": 66,
    "might": 64,
    "wisdom": 82,
    "charisma": 80
  },
  {
    "id": 94,
    "star": "地平星",
    "nickname": "铁臂膊",
    "name": "蔡福",
    "role": "行刑刽子 / Executioner",
    "weapon": "鬼头大刀",
    "signature": "北京两院押狱兼刽子手",
    "command": 68,
    "might": 81,
    "wisdom": 68,
    "charisma": 71
  },
  {
    "id": 95,
    "star": "地损星",
    "nickname": "一枝花",
    "name": "蔡庆",
    "role": "行刑刽子 / Executioner",
    "weapon": "鬼头刀",
    "signature": "鬓插一枝花，兄弟同心",
    "command": 63,
    "might": 77,
    "wisdom": 63,
    "charisma": 70
  },
  {
    "id": 96,
    "star": "地奴星",
    "nickname": "催命判官",
    "name": "李立",
    "role": "北山酒店 / Innkeeper",
    "weapon": "短刀",
    "signature": "揭阳岭黑店，眼利手快",
    "command": 58,
    "might": 73,
    "wisdom": 56,
    "charisma": 57
  },
  {
    "id": 97,
    "star": "地察星",
    "nickname": "青眼虎",
    "name": "李云",
    "role": "城垣营造 / Builder",
    "weapon": "朴刀",
    "signature": "青眼威猛，都头出身",
    "command": 70,
    "might": 80,
    "wisdom": 71,
    "charisma": 72
  },
  {
    "id": 98,
    "star": "地恶星",
    "nickname": "没面目",
    "name": "焦挺",
    "role": "步军将校 / Wrestler",
    "weapon": "拳脚",
    "signature": "三代相扑，擒摔见长",
    "command": 62,
    "might": 85,
    "wisdom": 57,
    "charisma": 63
  },
  {
    "id": 99,
    "star": "地丑星",
    "nickname": "石将军",
    "name": "石勇",
    "role": "步军将校 / Infantry",
    "weapon": "朴刀",
    "signature": "好赌任侠，敢赴危难",
    "command": 62,
    "might": 76,
    "wisdom": 55,
    "charisma": 69
  },
  {
    "id": 100,
    "star": "地数星",
    "nickname": "小尉迟",
    "name": "孙新",
    "role": "东山酒店 / Innkeeper",
    "weapon": "钢鞭",
    "signature": "登州军户，鞭枪兼使",
    "command": 70,
    "might": 79,
    "wisdom": 70,
    "charisma": 75
  },
  {
    "id": 101,
    "star": "地阴星",
    "nickname": "母大虫",
    "name": "顾大嫂",
    "role": "东山酒店 / Innkeeper",
    "weapon": "雌雄虎头刀",
    "signature": "性烈胆大，劫狱救亲",
    "command": 72,
    "might": 85,
    "wisdom": 72,
    "charisma": 83
  },
  {
    "id": 102,
    "star": "地刑星",
    "nickname": "菜园子",
    "name": "张青",
    "role": "西山酒店 / Innkeeper",
    "weapon": "扁担朴刀",
    "signature": "十字坡掌柜，识英雄惜好汉",
    "command": 64,
    "might": 74,
    "wisdom": 67,
    "charisma": 72
  },
  {
    "id": 103,
    "star": "地壮星",
    "nickname": "母夜叉",
    "name": "孙二娘",
    "role": "西山酒店 / Innkeeper",
    "weapon": "柳叶双刀",
    "signature": "十字坡豪侠，胆气泼辣",
    "command": 68,
    "might": 83,
    "wisdom": 66,
    "charisma": 81
  },
  {
    "id": 104,
    "star": "地劣星",
    "nickname": "活闪婆",
    "name": "王定六",
    "role": "北山酒店 / Innkeeper",
    "weapon": "走线铜锤",
    "signature": "行走轻捷，江边传信",
    "command": 61,
    "might": 71,
    "wisdom": 64,
    "charisma": 69
  },
  {
    "id": 105,
    "star": "地健星",
    "nickname": "险道神",
    "name": "郁保四",
    "role": "掌管帅旗 / Standard Bearer",
    "weapon": "梁山帅旗",
    "signature": "身长一丈，力举帅旗",
    "command": 70,
    "might": 83,
    "wisdom": 57,
    "charisma": 73
  },
  {
    "id": 106,
    "star": "地耗星",
    "nickname": "白日鼠",
    "name": "白胜",
    "role": "传令耳目 / Scout",
    "weapon": "酒瓢扁担",
    "signature": "黄泥冈卖酒，智取生辰纲",
    "command": 57,
    "might": 61,
    "wisdom": 72,
    "charisma": 67
  },
  {
    "id": 107,
    "star": "地贼星",
    "nickname": "鼓上蚤",
    "name": "时迁",
    "role": "机密探报 / Infiltrator",
    "weapon": "飞檐钩索",
    "signature": "飞檐走壁，盗甲放火",
    "command": 70,
    "might": 70,
    "wisdom": 92,
    "charisma": 78
  },
  {
    "id": 108,
    "star": "地狗星",
    "nickname": "金毛犬",
    "name": "段景住",
    "role": "马匹采办 / Horse Buyer",
    "weapon": "套马索",
    "signature": "识尽好马，盗取照夜玉狮子",
    "command": 60,
    "might": 65,
    "wisdom": 72,
    "charisma": 68
  }
];
